'use client';\nimport React, { useEffect, useMemo, useState } from "react";\nimport { Check, Timer, Gauge, Cpu, Wrench, Building2, Shield, Truck, BarChart3, Sparkles, Phone, Mail, MapPin, Menu, LogIn, LogOut, ChevronRight, Filter } from "lucide-react";\n\nexport default function Page(){ return <CalisenseMVP/> }\n\nfunction linkCls(route, me){ const base="hover:text-black"; return route===me?`text-black ${base}`:`text-gray-600 ${base}`;}
function HeroMetricsCard(){return (<div className="relative"><div className="aspect-[4/3] w-full rounded-3xl border bg-white p-6 shadow-xl"><div className="grid h-full grid-cols-2 gap-4">{["Basınç","Sıcaklık","Tork","Elektriksel"].map(k=>(<div key={k} className="flex flex-col justify-between rounded-2xl border p-4"><div className="text-sm font-medium text-gray-500">{k}</div><div className="text-3xl font-bold">±{k==="Elektriksel"?"0.05":"0.1"}%</div><div className="text-xs text-gray-500">Doğruluk sınıfı</div></div>))}</div></div><div className="pointer-events-none absolute -bottom-4 -right-4 rounded-2xl border bg-white px-4 py-2 text-xs shadow-md">Sensor Health™ skor kartı örneği</div></div>);}
function KPIGrid(){return (<div className="grid grid-cols-1 gap-4 md:grid-cols-4">{[["Aktif Sensör","128"],["Ortalama Sağlık","86/100"],["Drift>1%","7"],["30g İçinde Due","12"]].map(([label,val])=> (<div key={label} className="rounded-2xl border bg-white p-5"><div className="text-sm text-gray-500">{label}</div><div className="mt-1 text-3xl font-semibold tracking-tight">{val}</div></div>))}</div>);}
function HealthCard({title,value}){ const angle=Math.round((value/100)*360); return (<div className="rounded-2xl border bg-white p-6"><div className="text-sm text-gray-500">{title}</div><div className="mt-4 flex items-center gap-4"><div className="h-20 w-20 rounded-full" style={{background:`conic-gradient(rgb(17 24 39) ${angle}deg, rgb(229 231 235) ${angle}deg 360deg)`}}/><div><div className="text-4xl font-semibold leading-none">{value}</div><div className="text-xs text-gray-500 mt-1">/100</div></div></div></div>);}
function MiniTrend({title,value,note}){return (<div className="rounded-2xl border bg-white p-6"><div className="text-sm text-gray-500">{title}</div><div className="mt-3 text-3xl font-semibold">{value}</div>{note&&<div className="mt-1 text-xs text-gray-500">{note}</div>}</div>);}
function SensorRanges(){
  const [sector,setSector]=useState("Otomotiv Test");
  const ranges={
    "Otomotiv Test":[{label:"Basınç",items:["0–1000 bar (yakıt/rail)","Vakum dahil çok nokta"]},{label:"Sıcaklık",items:["–40…+1200°C (fırın/egzoz)","+/–0.2…1.0°C"]},{label:"Tork/Kuvvet",items:["10–3000 Nm","0–100 kN"]},{label:"Elektriksel",items:["mV–1000 V, mA–1000 A","DAQ kanal lineerliği"]}],
    "Savunma & Ar-Ge":[{label:"Basınç",items:["0–1600 bar (özel)","Hassas belirsizlik ±0.05% FS"]},{label:"Sıcaklık",items:["–80…+650°C","IR doğrulama"]},{label:"Akış/Proses",items:["Gaz/sıvı kütlesel","Sızdırmazlık testleri"]},{label:"Gaz/Çevresel",items:["O2/CO/CO2/H2/VOC","%RH ±2"]}],
    "Enerji & Rafineri":[{label:"Basınç",items:["0–2500 bar","Yüksek sıcaklık kompanzasyon"]},{label:"Sıcaklık",items:["–20…+1200°C","Termokupl K/J/T"]},{label:"Akış/Proses",items:["DN15–DN300 debimetre","Kütlesel/volümetrik hat"]},{label:"Elektriksel",items:["Ex-proof saha cihazları","Frekans/sinyal"]}],
    "Gıda & İlaç":[{label:"Sıcaklık",items:["–40…+180°C (soğuk zincir)","Datalogger doğrulama"]},{label:"Basınç",items:["0–25 bar (proses)","Diferansiyel basınç"]},{label:"Gaz/Çevresel",items:["CO2, O2, nem","GMP uyumlu kayıt"]},{label:"Elektriksel",items:["Temel elektriksel doğrulamalar","Kritik ekipman"]}],
  };
  const sectors=Object.keys(ranges);
  return (<section id="sensors" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-2xl font-bold md:text-3xl">Sektöre Göre Sensör Aralıkları</h2><p className="mt-2 max-w-3xl text-gray-600">Aralık ve doğruluklar proje ihtiyacına göre genişletilebilir. Talep edilirse özel menzil/prosedür tanımlarız.</p><div className="mt-4"><select value={sector} onChange={e=>setSector(e.target.value)} className="rounded-xl border px-3 py-2">{sectors.map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-2">{ranges[sector].map(({label,items})=>(<div key={label} className="rounded-2xl border p-6"><h3 className="text-lg font-semibold">{label}</h3><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-gray-700">{items.map(x=><li key={x}>{x}</li>)}</ul></div>))}</div><p className="mt-6 text-sm text-gray-500">Not: Değerler örnektir; kalibrasyon matrisi TÜRKAK kapsamına göre güncellenir.</p></section>);
}
function SensorTable(){
  const [q,setQ]=useState("");
  const data=useMemo(()=>[
    { id:"PRS-204", type:"Basınç", loc:"İzmit", last:"2025-09-04", drift:0.3, health:92, next:"2026-03-05", status:"OK" },
    { id:"TMP-442", type:"Sıcaklık", loc:"Gebze", last:"2025-07-12", drift:1.3, health:74, next:"2025-12-15", status:"Due" },
    { id:"TRQ-118", type:"Tork", loc:"Bursa", last:"2025-05-21", drift:0.8, health:81, next:"2025-11-27", status:"Soon" },
    { id:"ELC-331", type:"Elektriksel", loc:"Kartal", last:"2025-08-09", drift:0.2, health:95, next:"2026-02-10", status:"OK" },
    { id:"PRS-207", type:"Basınç", loc:"Derince", last:"2025-06-03", drift:1.8, health:69, next:"2025-11-10", status:"Due" },
  ],[]);
  const filtered=useMemo(()=>{ if(!q) return data; const k=q.toLowerCase(); return data.filter(r=>Object.values(r).join(" ").toLowerCase().includes(k)); },[q,data]);
  return (<div className="mt-8 rounded-2xl border bg-white p-6">
    <div className="mb-4 flex items-center justify-between gap-3"><div className="text-lg font-semibold">Sensör Listesi</div><div className="flex items-center gap-2"><div className="relative"><span className="pointer-events-none absolute left-2 top-2.5"><svg width="16" height="16"></svg></span><input placeholder="Ara: ID / tür / lokasyon" value={q} onChange={e=>setQ(e.target.value)} className="w-64 rounded-xl border px-3 py-2 text-sm outline-none focus:ring"/></div></div></div>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-gray-500"><tr className="border-b">{["ID","Tür","Lokasyon","Son Kalibrasyon","Drift %","Health","Sonraki","Durum",""].map(h=><th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{filtered.map(r=>(<tr key={r.id} className="border-b last:border-0"><td className="px-3 py-2 font-medium">{r.id}</td><td className="px-3 py-2">{r.type}</td><td className="px-3 py-2">{r.loc}</td><td className="px-3 py-2">{r.last}</td><td className="px-3 py-2">{r.drift.toFixed(1)}%</td><td className="px-3 py-2">{r.health}</td><td className="px-3 py-2">{r.next}</td><td className="px-3 py-2"><span className={"inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs "+(r.status==="OK"?"bg-green-50 text-green-700 border border-green-200":r.status==="Soon"?"bg-amber-50 text-amber-700 border border-amber-200":"bg-red-50 text-red-700 border border-red-200")}>{r.status}</span></td><td className="px-3 py-2"><a href="#" className="inline-flex items-center gap-1 text-sm text-gray-700 hover:text-black">Detay</a></td></tr>))}</tbody></table></div>
  </div>);
}
function PartnerList(){ const partners=[{name:"Marmara Kalibrasyon",city:"Kocaeli",areas:["Basınç","Sıcaklık"],sla:"48s"},{name:"Bursa Metrotech",city:"Bursa",areas:["Tork","Elektriksel"],sla:"72s"},{name:"Istanbul Q-Lab",city:"İstanbul",areas:["Elektriksel","Basınç"],sla:"24s"}]; return (<div className="rounded-2xl border p-6 shadow-sm"><div className="mb-3 text-lg font-semibold">Onaylı Hizmet Sağlayıcılar</div><ul className="space-y-3 text-sm">{partners.map(p=>(<li key={p.name} className="flex items-center justify-between rounded-xl border px-3 py-2"><div><div className="font-medium">{p.name}</div><div className="text-gray-500">{p.city} · {p.areas.join(" · ")}</div></div><div className="text-gray-600">SLA: {p.sla}</div></li>))}</ul><a href="#contact" className="mt-4 inline-flex items-center justify-center rounded-2xl bg-black px-4 py-2 text-sm font-medium text-white">Teklif Talep Et</a></div>);}
function PartnerApply(){ const [lab,setLab]=useState(""); const [city,setCity]=useState(""); const [areas,setAreas]=useState([]); const msg=`Merhaba, partner başvurusu yapmak istiyoruz.\n\nLaboratuvar: ${lab}\nŞehir: ${city}\nAlanlar: ${areas.join(", ")}`; const href=`mailto:partners@calisense.com?subject=Partner%20Başvurusu&body=${encodeURIComponent(msg)}`; const toggle=a=>setAreas(prev=>prev.includes(a)?prev.filter(x=>x!==a):[...prev,a]); return (<div className="rounded-2xl border p-6 shadow-sm"><div className="mb-3 text-lg font-semibold">Partner Başvurusu</div><div className="space-y-3 text-sm"><label className="block">Laboratuvar Adı<input value={lab} onChange={e=>setLab(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><label className="block">Şehir<input value={city} onChange={e=>setCity(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><fieldset><legend className="mb-1 text-gray-600">Alanlar</legend><div className="flex flex-wrap gap-2">{["Basınç","Sıcaklık","Tork","Elektriksel"].map(a=>(<button type="button" key={a} onClick={()=>toggle(a)} className={"rounded-full border px-3 py-1 "+(areas.includes(a)?"bg-black text-white":"bg-white text-gray-800 hover:bg-gray-50")}>{a}</button>))}</div></fieldset><a href={href} className="inline-flex items-center justify-center rounded-2xl bg-black px-4 py-2 font-medium text-white">Başvuruyu Gönder</a><p className="text-xs text-gray-500">Gönder butonu e-posta uygulamanızı açar.</p></div></div>);}
function CalisenseMVP(){
  const [open,setOpen]=useState(false);
  const [email,setEmail]=useState("");
  const [message,setMessage]=useState("");
  const [loggedIn,setLoggedIn]=useState(false);
  const [route,setRoute]=useState(()=>(typeof window!=="undefined"?window.location.hash.replace("#",""):"")||"home");
  useEffect(()=>{ const onHash=()=>setRoute(window.location.hash.replace("#","")||"home"); window.addEventListener("hashchange",onHash); return ()=>window.removeEventListener("hashchange",onHash);},[]);
  return (<div className="min-h-screen bg-white text-gray-900">
    <header className="sticky top-0 z-40 w-full border-b bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 md:py-4"><a href="#home" onClick={()=>setRoute("home")} className="flex items-center gap-2 font-semibold"><Gauge className="h-6 w-6"/><span>Calisense</span></a><nav className="hidden items-center gap-6 md:flex"><a href="#services" onClick={()=>setRoute("services")} className={linkCls(route,"services")}>Hizmetler</a><a href="#dashboard" onClick={()=>setRoute("dashboard")} className={linkCls(route,"dashboard")}>Dashboard</a><a href="#partners" onClick={()=>setRoute("partners")} className={linkCls(route,"partners")}>Partnerler</a><a href="#partner-apply" onClick={()=>setRoute("partner-apply")} className={linkCls(route,"partner-apply")}>Başvuru</a><a href="#pricing" onClick={()=>setRoute("pricing")} className={linkCls(route,"pricing")}>Paketler</a><a href="#contact" onClick={()=>setRoute("contact")} className={linkCls(route,"contact")}>İletişim</a></nav><div className="flex items-center gap-2"><button onClick={()=>setLoggedIn(v=>!v)} className="inline-flex items-center gap-2 rounded-2xl border px-3 py-1.5 text-sm hover:bg-gray-50" aria-label={loggedIn?"Çıkış Yap":"Giriş Yap"}>{loggedIn?<LogOut className="h-4 w-4"/>:<LogIn className="h-4 w-4"/>}{loggedIn?"Çıkış":"Giriş"}</button><button onClick={()=>setOpen(!open)} className="md:hidden"><Menu className="h-6 w-6"/></button></div></div>{open&&<div className="border-t bg-white md:hidden"><div className="mx-auto flex max-w-7xl flex-col px-4 py-3">{[["home","Anasayfa"],["services","Hizmetler"],["dashboard","Dashboard"],["partners","Partnerler"],["partner-apply","Başvuru"],["pricing","Paketler"],["contact","İletişim"]].map(([r,label])=>(<a key={r} href={`#${r}`} className="py-2" onClick={()=>{setOpen(false); setRoute(r);}}>{label}</a>))}</div></div>}</header>
    <section id="home" className="relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-teal-50"/><div className="relative mx-auto grid max-w-7xl grid-cols-1 items-center gap-8 px-4 py-16 md:grid-cols-2 md:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium"><Sparkles className="h-3.5 w-3.5"/>Mobil + Dijital Kalibrasyon</div><h1 className="mt-4 text-3xl font-bold leading-tight md:text-5xl">Sensör Kalibrasyonunda <span className="text-blue-600">Hız</span>,<br className="hidden md:block"/> Güvenirlik ve <span className="text-teal-600">Dijital Sertifika</span></h1><p className="mt-4 text-gray-600 md:text-lg">Kocaeli merkezli mobil ekip, İstanbul ve Bursa’ya aynı gün servis. ISO/IEC 17025 uyumlu süreç, QR’lı dijital sertifika ve Sensor Health™ skoru ile kalibrasyona yeni standart.<br/><span className="text-gray-700">Amacımız: Türkiye’deki <strong>tüm kalibrasyon ofislerini tek bir hizmet çatısı altında</strong> birleştirip, müşteriye hız ve şeffaflık sağlayan bir platform sunmak.</span></p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href="#dashboard" onClick={()=>setRoute("dashboard")} className="inline-flex items-center justify-center rounded-2xl bg-black px-5 py-3 font-medium text-white shadow-md hover:shadow-lg">Canlı Dashboard (Demo)</a><a href="#pricing" onClick={()=>setRoute("pricing")} className="inline-flex items-center justify-center rounded-2xl border px-5 py-3 font-medium hover:bg-gray-50">Paketleri Gör</a></div><div className="mt-6 grid grid-cols-2 gap-4 text-sm text-gray-700 md:grid-cols-3"><div className="flex items-center gap-2"><Timer className="h-4 w-4"/> 48 saatte teslim*</div><div className="flex items-center gap-2"><Shield className="h-4 w-4"/> 17025 uyumlu süreç</div><div className="flex items-center gap-2"><Truck className="h-4 w-4"/> Mobil laboratuvar</div></div></div>{HeroMetricsCard()}</div></section>
    <section id="services" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-2xl font-bold md:text-3xl">Hizmetler</h2><p className="mt-2 max-w-2xl text-gray-600">Kalibrasyonun ötesinde; veri, hız ve dijital doğrulama.</p><div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-3">{[{icon:"Gauge", title:"Sensör Kalibrasyonu", items:["Basınç (0–600 bar)","Sıcaklık (–40…+650°C)","Tork (10–1000 Nm)","Volt/Amp/Ohm"]},{icon:"BarChart3", title:"Dijital Sertifika & QR", items:["QR ile doğrulama","Bulut arşiv","Denetim raporu","API erişimi"]},{icon:"Cpu", title:"Sensor Health™ Analitiği", items:["Drift takibi","Öngörücü bakım","Abonelik paneli","Uyarı/hatırlatma"]}].map((s)=> (<div key={s.title} className="rounded-2xl border p-6 shadow-sm"><div className="mb-3 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-gray-900 text-white">{s.title==="Sensör Kalibrasyonu"?<Gauge className="h-5 w-5"/>:s.title==="Dijital Sertifika & QR"?<BarChart3 className="h-5 w-5"/>:<Cpu className="h-5 w-5"/>}</div><h3 className="text-lg font-semibold">{s.title}</h3><ul className="mt-3 space-y-2 text-sm text-gray-700">{s.items.map(i=>(<li key={i} className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4 text-gray-900"/> {i}</li>))}</ul></div>))}</div></section>
    {SensorRanges()}
    <section id="dashboard" className="border-y bg-gray-50"><div className="mx-auto max-w-7xl px-4 py-14"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-bold md:text-3xl">Sensor Health™ Dashboard</h2><div className="flex items-center gap-2 text-sm"><span className="hidden md:inline text-gray-600">Durum: {loggedIn?"Demo veriler aktif":"Giriş yapılmadı (demo görünümü)"}</span><button onClick={()=>setLoggedIn(v=>!v)} className="inline-flex items-center gap-2 rounded-2xl border px-3 py-1.5 hover:bg-white">{loggedIn?<LogOut className="h-4 w-4"/>:<LogIn className="h-4 w-4"/>} {loggedIn?"Çıkış":"Demo Girişi"}</button></div></div>{KPIGrid()}<div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-3">{HealthCard({title:"Genel Sağlık Skoru",value:86})}{MiniTrend({title:"Aylık Drift Ort.",value:"+0.42%",note:"Son 6 ay"})}{MiniTrend({title:"Yaklaşan Kalibrasyonlar",value:"12 cihaz",note:"30 gün içinde"})}</div>{SensorTable()}</div></section>
    <section id="partners" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-2xl font-bold md:text-3xl">Laboratuvar Partner Ağı</h2><p className="mt-2 max-w-2xl text-gray-600">Türkiye genelindeki kalibrasyon laboratuvarlarını tek platformda buluşturuyoruz. Başvurun, doğrulama sonrası paneliniz açılsın.</p><div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-3"><div className="rounded-2xl border p-6 shadow-sm"><div className="mb-3 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-gray-900 text-white"><Building2 className="h-5 w-5"/></div><h3 className="text-lg font-semibold">Neden Katılın?</h3><ul className="mt-3 space-y-2 text-sm text-gray-700"><li className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4"/> Bölgenizdeki kurumsal talebe erişim</li><li className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4"/> QR'lı dijital sertifika altyapısı</li><li className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4"/> API ile kolay entegrasyon</li></ul></div>{PartnerList()}{PartnerApply()}</div></section>
    <section id="partner-apply" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-2xl font-bold md:text-3xl">Partner Başvurusu</h2><p className="mt-2 max-w-2xl text-gray-600">Platform hedefimiz: <strong>tüm kalibrasyon ofislerini birleştirmek</strong>. Aşağıdaki formu doldurun; doğrulama sonrası panelinizi açalım.</p><form action="https://formspree.io/f/REPLACE_WITH_YOUR_ID" method="POST" data-netlify="true" name="partner-apply" className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2"><label className="text-sm">Laboratuvar Adı<input name="lab" required className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><label className="text-sm">Şehir<input name="city" required className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><label className="text-sm">E-posta<input type="email" name="email" required className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><label className="text-sm">Telefon<input name="phone" className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><fieldset className="md:col-span-2"><legend className="mb-1 text-sm text-gray-600">Alanlar</legend><div className="flex flex-wrap gap-2 text-sm">{["Basınç","Sıcaklık","Tork","Elektriksel","Akış/Proses","Gaz/Çevresel"].map(a=>(<label key={a} className="inline-flex items-center gap-2 rounded-full border px-3 py-1"><input type="checkbox" name="areas" value={a}/> {a}</label>))}</div></fieldset><label className="text-sm md:col-span-2">Akreditasyon (varsa)<select name="accreditation" className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"><option>Seçiniz</option><option>ISO/IEC 17025 (TÜRKAK)</option><option>Diğer</option><option>Yok / Başvuru aşamasında</option></select></label><label className="text-sm md:col-span-2">Web Sitesi<input name="website" className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring" placeholder="https://"/></label><label className="text-sm md:col-span-2">Mesajınız<textarea name="message" rows={5} className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring" placeholder="Kapasite, ekipman, kapsam açıklaması"/></label><input type="hidden" name="form-name" value="partner-apply"/><button className="md:col-span-2 inline-flex items-center justify-center rounded-2xl bg-black px-5 py-3 font-medium text-white hover:shadow">Başvuruyu Gönder</button><p className="md:col-span-2 text-xs text-gray-500">Not: Formspree kullanıyorsanız URL'deki ID'yi değiştirin. Netlify kullanıyorsanız gönderimler Netlify'da görünür.</p></form></section>
    <section id="pricing" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-2xl font-bold md:text-3xl">Paketler</h2><p className="mt-2 max-w-2xl text-gray-600">Aylık üyelikle bütçe öngörülebilirliği ve hızlı servis.</p><div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-3">{[{name:"Base",price:"₺4.990/ay",badge:"Yeni Başlayanlar",features:["Aylık 10 cihaza kadar","Standart kalibrasyon","Dijital sertifika arşivi","48 saatte teslim*"]},{name:"Pro",price:"₺12.900/ay",badge:"En Popüler",features:["Aylık 30 cihaza kadar","Öncelikli mobil servis","QR doğrulama + API","Sensor Health™ panel"]},{name:"Enterprise",price:"Teklif",badge:"Ölçekli Operasyon",features:["Sınırsız cihaz/tesiste fiyatlama","Öngörücü bakım analitiği","Denetim/uyumluluk raporları","SLA ile garanti"]}].map(p=>(<div key={p.name} className="relative rounded-2xl border p-6 shadow-sm"><div className="absolute -top-3 right-4 rounded-full border bg-white px-3 py-1 text-xs font-medium">{p.badge}</div><h3 className="text-lg font-semibold">{p.name}</h3><div className="mt-1 text-3xl font-bold">{p.price}</div><ul className="mt-4 space-y-2 text-sm text-gray-700">{p.features.map(f=>(<li key={f} className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4 text-gray-900"/> {f}</li>))}</ul><a href="#contact" className="mt-6 inline-flex w-full items-center justify-center rounded-2xl bg-black px-4 py-2 font-medium text-white hover:shadow">Seç ve İletişime Geç</a></div>))}</div><p className="mt-4 text-xs text-gray-500">*Teslim süresi cihaz türü ve yoğunluğa göre değişebilir.</p></section>
    <section className="border-y bg-gradient-to-br from-gray-50 to-white"><div className="mx-auto grid max-w-7xl grid-cols-1 items-center gap-6 px-4 py-12 md:grid-cols-2"><div><h3 className="text-xl font-semibold md:text-2xl">Kalibrasyonda yeni bir standart deneyimleyin</h3><p className="mt-2 text-gray-600">Mobil ekip, dijital sertifika, Sensor Health™ skoru. Kocaeli çıkışlı hızlı servis.</p><div className="mt-4 flex flex-wrap gap-3 text-sm text-gray-700"><div className="inline-flex items-center gap-2 rounded-full border px-3 py-1"><Wrench className="h-4 w-4"/> Yerinde servis</div><div className="inline-flex items-center gap-2 rounded-full border px-3 py-1"><Shield className="h-4 w-4"/> Uyumlu süreç</div><div className="inline-flex items-center gap-2 rounded-full border px-3 py-1"><BarChart3 className="h-4 w-4"/> Health skoru</div></div></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><form action="https://formspree.io/f/REPLACE_WITH_YOUR_ID" method="POST" data-netlify="true" name="contact" className="grid grid-cols-1 gap-3"><label className="text-sm">E-posta<input type="email" name="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="ornek@firma.com" className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><label className="text-sm">İhtiyacınızı Anlatın<textarea name="message" value={message} onChange={e=>setMessage(e.target.value)} rows={4} placeholder="Cihaz tipi, adet, lokasyon..." className="mt-1 w-full rounded-xl border px-3 py-2 outline-none focus:ring"/></label><input type="hidden" name="form-name" value="contact"/><button type="submit" className="inline-flex items-center justify-center rounded-2xl bg-black px-4 py-2 font-medium text-white hover:shadow">Teklif Talep Et</button><p className="mt-2 text-xs text-gray-500">Form gönderimleri e-posta inbox'ınıza düşer. Formspree/Netlify yapılandırması gerektirir.</p></form></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-2xl font-bold md:text-3xl">Sık Sorulan Sorular</h2><div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">{[["Akreditasyon durumunuz nedir?","ISO/IEC 17025’e uyumlu süreçle çalışıyoruz; akreditasyon başvuru takvimimiz yayında. Kurumsal müşterilere süreç şeffaflığı sağlanır."],["Hangi bölgelerde hizmet veriyorsunuz?","Kocaeli merkezli olup İstanbul ve Bursa’ya aynı gün mobil servis sunuyoruz."],["Sertifikalar nasıl doğrulanır?","Her sertifikada QR bulunur. Tarattığınızda geçerlilik ve detaylar bulutta görüntülenir."],["Fiyatlandırma nasıl?","Paketler aylık üyelik mantığındadır; tek seferlik kalibrasyon için de teklif veriyoruz."]].map(([q,a])=>(<div key={q} className="rounded-2xl border p-5"><div className="font-semibold">{q}</div><div className="mt-1 text-gray-600">{a}</div></div>))}</div></section>
    <footer className="border-t"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-6 px-4 py-10 md:grid-cols-3"><div><div className="flex items-center gap-2 font-semibold"><Gauge className="h-5 w-5"/> Calisense</div><p className="mt-2 text-sm text-gray-600">Mobil & dijital sensör kalibrasyonu. Kocaeli · İstanbul · Bursa.</p><div className="mt-3 flex flex-col gap-2 text-sm text-gray-700"><div className="flex items-center gap-2"><Phone className="h-4 w-4"/> +90 532 000 00 00</div><div className="flex items-center gap-2"><Mail className="h-4 w-4"/> hello@calisense.com</div><div className="flex items-center gap-2"><MapPin className="h-4 w-4"/> Kartepe, Kocaeli</div></div></div><div><div className="font-semibold">Bağlantılar</div><ul className="mt-2 space-y-2 text-sm text-gray-700"><li><a href="#services" className="hover:text-black">Hizmetler</a></li><li><a href="#pricing" className="hover:text-black">Paketler</a></li><li><a href="#partners" className="hover:text-black">Partnerler</a></li><li><a href="#dashboard" className="hover:text-black">Dashboard</a></li></ul></div><div id="contact"><div className="font-semibold">Hızlı İletişim</div><p className="mt-2 text-sm text-gray-600">İhtiyacınızı paylaşın, aynı gün dönüş yapalım.</p><a href="#contact" className="mt-3 inline-flex items-center justify-center rounded-2xl bg-black px-4 py-2 text-sm font-medium text-white">Teklif Al</a></div></div><div className="border-t py-4 text-center text-xs text-gray-500">© {new Date().getFullYear()} Calisense. Tüm hakları saklıdır.</div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness","name":"Calisense","description":"Mobil ve dijital sensör kalibrasyon hizmetleri: basınç, sıcaklık, tork, elektriksel. ISO/IEC 17025 uyumlu süreç, QR'lı dijital sertifika.","address":{"@type":"PostalAddress","addressLocality":"Kartepe","addressRegion":"Kocaeli","addressCountry":"TR"},"areaServed":["Kocaeli","İstanbul","Bursa"],"url":"https://calisense.local/mvp","telephone":"+90 532 000 00 00","sameAs":[]})}}/>
  </div>);
}
